### PR TITLE
Update supabase-js to latest version -> fixed https://github.com/hiro1107/nestjs-supabase-auth/issues/7 + Code cleanup

### PR DESCRIPTION
**Pull request by Gamekohl**
I've updated supbabase-js to the latest version to resolve this bug (https://github.com/hiro1107/nestjs-supabase-auth/issues/7). Also I cleaned up the code, hence removed the validateSupabaseResponse function and put the code directly into the validate function.

### CODE REVIEW

**Comment by NicolasDiazDuarte** [comment]
It works

**Comment by gamedevsam** [comment]
Any reason why this shouldn't get merged? Seems like a useful fix.

**Comment by hmtcelik** [comment]
waiting to merge, any update ?

**Review by Farischt — APPROVED** [review]

**Comment by Farischt** [comment]
@hiro1107 Need this one to be merged asap

**Comment by gamedevsam** [comment]
Looks like this repo maybe stale, it's worth trying to make a fork the canonical / active version of the package. We might be able to reach out to NPM to swap owners of the library, or we could just publish it as a new package. Thoughts?

**Comment by Farischt** [comment]
@gamedevsam  Created my own guard if someone needs it:

```ts 
auth.guard.ts

@Injectable()
export class GqlAuthGuard implements CanActivate {
  public async canActivate(context: ExecutionContext): Promise<boolean> {
    const ctx = GqlExecutionContext.create(context);

    const request = ctx.getContext().req as GraphQLRequest;

    const { authorization } = request.headers;
    if (!authorization || authorization.trim() === '') {
      throw new UnauthorizedException('Missing authorization header');
    }

    const jwt = authorization.replace(/bearer/gim, '').trim();
    const { data, error } = await supabase.auth.getUser(jwt);

    if (error) {
      throw new UnauthorizedException('Invalid or expired token');
    }

    request.user = data.user;
    return true;
  }
}
```

```ts

auth.decorator.ts

import { createParamDecorator, ExecutionContext } from '@nestjs/common';
import { GqlExecutionContext } from '@nestjs/graphql';

export const GqlAuthUser = createParamDecorator(
  (_data: unknown, context: ExecutionContext) => {
    const ctx = GqlExecutionContext.create(context);
    return ctx.getContext().req?.user;
  },
);
```

fyi supabase is created in another folder
Feel free to ping me if needed !

**Comment by tgirotto** [comment]
forked and merged at https://github.com/tgirotto/nestjs-supabase-auth-v2

**Comment by hiro1107** [comment]
@tgirotto 
Thank you for creating the PR, and I'm sorry it took such a long time to review. I plan to add another maintener to this repo so the repo will be keep updated.

**Pull request merged**
